### PR TITLE
Enable upload JSON character sheet

### PR DESCRIPTION
**Pull request by edreeseg**
Currently, when our /upload page is hit, we end up getting a lovely 'Argument 'UploadCtrl' is not a function, got undefined' error. This seems to be because we are not embedding our upload.js script in index.html. This fixes that, allowing the upload to proceed as planned.

Max file size was bumped from 15,000 to 35,000 as, anecdotally as a frequent user of this app, I do have character sheets that go over the previous max, so this seems reasonable to me. If this size bump isn't acceptable it can be omitted.

Please let me know if there are any questions, or if I'm missing something and perhaps this script was purposefully not embedded at this time.

Thanks, have a great day.

### CODE REVIEW

**Comment by maxluoXIII** [comment]
Your code looks fine, but I'm having trouble building using 'grunt build'. The issue seems to be the [backtick in the upload.js file]( https://github.com/Mottokrosh/Sheet/blob/9df19b5728b3a9755ee17554dade6834a22e4440/app/scripts/controllers/upload.js#L81). Is it working on your end? I just want to make sure we don't end up pushing code that would bring down the site.

If you're also having issues, I think it would probably be solved by just doing normal string concatenation there instead. Otherwise, I'll have to look into why my environment isn't working...

**Comment by edreeseg** [comment]
@maxluoXIII Nice catch, thank you very much! I suppose that wasn't caught because this feature was never fully incorporated.

Went ahead and changed that, and grunt build appears to be going through without issue now.

Please let me know if you run into any other issues. I checked for additional template literal use, but didn't turn anything else up in the repo.

Thanks again, take care!

**Comment by maxluoXIII** [comment]
Looks good! I think the only thing left is that I believe we want to check in the built site (the 'dist' folder) into the Git repo because the pipeline doesn't do that, but we should probably defer to @Mottokrosh as to whether that's accurate.

**Comment by Mottokrosh** [comment]
Yes, I believe that's correct. I think way back when I first started this, there wasn't much in the way of CI on Heroic yet, so that was the easiest.

**Comment by edreeseg** [comment]
@Mottokrosh Thanks for clarifying. I've included the contents of `dist`. I hope thing look how they should, please let me know if I'm missing anything,

**Comment by Mottokrosh** [comment]
LGTM. Feel free to merge and push to Heroku. I believe you have access and the power, @maxluoXIII?

**Comment by maxluoXIII** [comment]
I think you forgot to include dist/index.html. The changes don't seem to apply until I do another grunt build, and it seems like you're still [referencing the old generated script file](https://github.com/edreeseg/Sheet/blob/5aeee6eeb37a3f9b9c60970c41f1a37cdcb7c4cf/dist/index.html#L51) (scripts/9c7087d8.scripts.js instead of scripts/6905e63e.scripts.js).

**Comment by Mottokrosh** [comment]
Oh man, that shows how sleepy my brain was this morning. Thanks for spotting this. 😄

**Comment by maxluoXIII** [comment]
Thanks for looking into it. Not sure how, but your build somehow deleted the bower_components and the site doesn't work. Another 'grunt build' solved the issue on my end. If you're having troubles, I could try making a PR to your fork? Otherwise if you need a reference, the dist folder should look like [this](https://github.com/maxluoXIII/Sheet/tree/enable-json-upload/dist).

No worries about all the extra changes; the pipeline is a bit confusing and maintaining a clean git history isn't a huge priority.

**Comment by edreeseg** [comment]
@maxluoXIII Sure thing. I've changed machines since last I touched this, and didn't realize bower wasn't installed. That'd probably be why. Looks like the structure matches up with the most recent commit - sorry again for the inconvenience.

**Comment by maxluoXIII** [comment]
LGTM! 😃

**Pull request merged**
