### PR TITLE
Upload character sheet

### PR DESCRIPTION
**Pull request by JaredClayborn**
As a DM that requires users to send their character sheets, I would like to have the ability to upload my players sheets to my account so that I can easily read them.

I added the ability to upload the JSON file that is exported so that I can easily view my players character sheets.

### CODE REVIEW

**Comment by Mottokrosh** [comment]
Why did I not see this before? So much for notifications!

Anyway, so sorry, will give it a test and merge if I don't spot any errors. Thanks for doing this!

**Comment by JaredClayborn** [comment]
No worries.  Let me know if this needs anything

**Comment by Mottokrosh** [comment]
I've tried to test it locally but I seem to be getting a database error when trying to do the insert after the upload. It could be a problem with my (dated) local setup though. I presume it's working for you?

**Comment by JaredClayborn** [comment]
Yes, sir.  I'll find some time today to spin it back up and make sure it
works, again.

**Comment by JaredClayborn** [comment]
I'm having a bit of trouble getting it to run locally again, as well.  I can keep trying, but it was working when I was developing.

**Comment by JaredClayborn** [comment]
Hey.  I got it working locally again.  I've switched computers since I created this PR, had to redo all the heroku stuff and find my google/github/mongodb stuff to fill in the env file.  Attaching a short video of the upload in a zip.  Let me know if you need anything, or have any questions.

[Pathfinder RPG Digital Character Sheet - Google Chrome 2020-05-22 08-26-59.zip](https://github.com/Mottokrosh/Sheet/files/4668286/Pathfinder.RPG.Digital.Character.Sheet.-.Google.Chrome.2020-05-22.08-26-59.zip)

.

**Comment by JaykeBird** [comment]
I actually created my own offline viewer/editor for the JSON files that this website creates. Having a way to upload these files back onto the website would be awesome! Much easier to use the share link off the website than sending back and forth JSON files. I'm just lucky most the players in my friend circle are computer-savvy!

**Comment by Mottokrosh** [comment]
> Hey. I got it working locally again. [...]

That's great @JaredClayborn! I'll try and get this merged this week finally. By the way, I am looking for a co-maintainer for this project, to get it moving faster again. Might that be something of interest to you?

@JaykeBird, cool! I'm really glad to see more outside activity surrounding this project!

**Comment by JaredClayborn** [comment]
@Mottokrosh Sorry, I didn't see that you had messaged.  I would be interested in helping to maintain. This is a really cool project.

**Pull request merged**
